apiVersion: batch/v1
kind: Job
metadata:
  name: jx-boot
spec:
  template:
    spec:
      serviceAccountName: jx-git-operator
      restartPolicy: Never
      containers:
      - name: jx-boot
        image: ghcr.io/jenkins-x/jx-boot:3.10.104
        imagePullPolicy: IfNotPresent
        command:
        - jx
        - boot
        - run
        env:
        - name: GIT_URL
          value: https://github.com/anna200417/wordpress-deploy.git
        - name: GIT_BRANCH
          value: main
