apiVersion: batch/v1
kind: Job
metadata:
  name: jx-boot
spec:
  template:
    spec:
      containers:
      - name: jx-boot
        image: ghcr.io/jenkins-x/jx-boot:3.10.122
        imagePullPolicy: IfNotPresent
        command:
        - jx
        - gitops
        - job
      restartPolicy: Never
